on:
  push:
    branches:
      - feature/**
    tags-ignore:
      - '**'
  pull_request:
    branches:
      - main
      - testing**
    types:
      - opened
      - closed
      - synchronize
    tags-ignore:
      - '**'

jobs:

  iac:
    uses: ./.github/workflows/iac.yml
    with:
      env: dev