name: IAC(1)

on:
  workflow_dispatch:
    inputs:
      db_username:
        description: "Database Username"
        required: true
      db_password:
        description: "Database Password"
        required: true
      db_root_password:
        description: "Root DB Password"
        required: true
      db_host:
        description: "Database Host"
        required: true
        default: "mariadb"
      db_port:
        description: "Database Port"
        required: true
        default: "3306"
      db_name:
        description: "Database Name"
        required: true
        default: "smotrish_db"
      flask_secret:
        description: "Flask Secret Key"
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./dev

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.8.5

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1


    - name: Terraform Apply
      env:
          TF_VAR_db_username: ${{ github.event.inputs.db_username }}
          TF_VAR_db_password: ${{ github.event.inputs.db_password }}
          TF_VAR_db_root_password: ${{ github.event.inputs.db_root_password }}
          TF_VAR_db_host: ${{ github.event.inputs.db_host }}
          TF_VAR_db_port: ${{ github.event.inputs.db_port }}
          TF_VAR_db_name: ${{ github.event.inputs.db_name }}
          TF_VAR_flask_secret: ${{ github.event.inputs.flask_secret }}
      run: terraform apply -var-file="terraform.tfvars" -auto-approve